[package]
name = "new_type"
version = "0.1.0"
authors = ["Silvan Buedenbender <silvan@claiv.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
